blog/app.py
from blog.article.views import article
from blog.report.views import report
from blog.user.views import user
from flask import (
    Flask,
    request
)


# app = Flask(__name__)
#
#
# @app.route("/", methods=["GET", "POST"])
# def index():
#     return f'This is a {request.method} '

def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprints(app)
    return app


def register_blueprints(app: Flask):
    app.register_blueprint(user)
    app.register_blueprint(report)
    app.register_blueprint(article)

blog/article/views.py
from flask import (
    Blueprint,
    render_template,
)
from werkzeug.exceptions import NotFound

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static', )

ARTICLES = [
    {
        'id': 1,
        'title': 'some title #1',
        'text': 'some text',
        'author': {
            'name': 'Alice',
            'id': 1,
        },
    },
    {
        'id': 2,
        'title': 'some title #2',
        'text': 'some text',
        'author': {
            'name': 'Jon',
            'id': 2,
        },
    }
]


@article.route('/')
def article_list():
    return render_template(
        'articles/list.html',
        articles=ARTICLES,
    )


@article.route('/<pk>')
def get_article(pk):
    try:
        pk = eval(pk)
        article_title = pk.get('title')
        article_text = pk.get('text')
        article_author_name = pk.get('author').get('name')
        article_author_id = pk.get('author').get('id')
    except KeyError:
        raise NotFound(f'Article {article_title} not found')
    return render_template(
        'articles/details.html',
        #article_id=article_id,
        article_title=article_title,
        article_text=article_text,
        article_author_name=article_author_name,
        article_author_id=article_author_id,
    )

blog/report/views.py
from blog.user.views import user
from flask import (
    Blueprint,
    render_template,
)

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static',)


@report.route('/')
def report_list():
    return render_template('reports/list.html', reports=[1, 2, 3, 4, 5])

blog/user/views.py
from flask import (
    Blueprint,
    render_template,
)
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static', )

USERS = {
    1: 'Alice',
    2: 'Jon',
    3: 'Mike',
}


@user.route('/')
def user_list():
    return render_template(
        'users/list.html',
        users=USERS,
    )


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        raise NotFound(f'User id {pk} not found')
    return render_template(
        'users/details.html',
        user_name=user_name,
    )

blog/templates/articles/details.html
{% extends 'base.html' %}

{% block title %}
    {{super()}}
Article detail
{% endblock %}

{% block body %}
<h1>{{ article_title }}</h1>
<h3>{{ article_text }}</h3>
<! -- if user_id = article_author_id -->
<h3><a href="{{url_for('user.get_user', pk=article_author_id) }}">{{ article_author_name }}</a></h3>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
Articles list
{% endblock %}

{% block body %}
<div class="row">
    <div class="col">
    {% for article in articles %}
        <ul>
            <li>
            <a href="{{ url_for('article.get_article', pk=article) }}">{{ article['id'] }} {{ article['title'] }}</a>
            </li>
        </ul>
    {% endfor %}
    </div>
  </div>
{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


      {% block css %}
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
      {% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
  {% include 'navbar.html' %}
  <div class="container">
  {% block body %}{% endblock %}
</div>

    {% block js %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  {% endblock %}
  </body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('user.user_list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.article_list') }}">Articles</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

blog/templates/reports/list.html
{% extends 'base.html' %}

{% block title %}
    Reports list
{% endblock %}

{% block body %}
<div class="row">
    <div class="col">
      <h1>Reports:</h1>
<!-- {{ url_for ('report.report_list') }} -->
    {% for report in reports %}
        <ul>
            <li>
                {{ report }}
            </li>
        </ul>
    {% endfor %}
    </div>
  </div>
{% endblock %}

blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    {{super()}}
User detail
{% endblock %}

{% block body %}
<h1>{{ user_name }}</h1>
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    {{super()}}
User list
{% endblock %}

{% block body %}
<div class="row">
    <div class="col">
      <h1>Users:</h1>
<!-- {{ url_for ('report.report_list') }} -->
    {% for user_id in users %}
        <ul>
            <li>
                <a href="{{url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a>
            </li>
        </ul>
    {% endfor %}
    </div>
  </div>
{% endblock %}